#include "RobotNav_PathTracking.hpp"
#include <iomanip>
#include <cstdlib>
#include <ctime>

//stack
stack::stack() {
    top = -1;
}

//Adds a new step movement on top of the stack
bool stack::push(stepMovement step) {
    if (isFull()) {
        cout << "Stack is full, cannot record more steps." << endl;
        return false;
    }
    steps[++top] = step;
    return true;
}

//Removes and returns the top step movement
stepMovement stack::pop() {
    if (isEmpty()) {
        cout << "Stack is empty. No steps to pop" << endl;
        stepMovement empty;
        empty.stepNumber = -1;
        empty.zone = "";
        empty.aisle = "";
        empty.shelf = "";
        return empty;
    }
    return steps[top--];
}

//Returns the top step movement without removing it
stepMovement stack::peek() {
    if (isEmpty()) {
        cout << "Stack is empty. No steps to peek" << endl;
        stepMovement empty;
        empty.stepNumber = -1;
        empty.zone = "";
        empty.aisle = "";
        empty.shelf = "";
        return empty;
    }
    return steps[top];
}

bool stack::isEmpty() {
    return top == -1;
}

bool stack::isFull() {
    return top == max_Steps -1;
}

int stack::getSize() {
    return top + 1;
}

//Prints all steps for the forward path
void stack::displayAll() {
    if (isEmpty()) {
        cout << "No steps recorded." << endl;
        return; 
    }

    cout << left
        << setw(8) << "Step"
        << setw(16) << "Zone"
        << setw(16) << "Aisle"
        << setw(16) << "Shelf" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;

    for (int i = 0; i <= top; i++) {
        cout << left
            << setw(8) << steps[i].stepNumber
            << setw(16) << steps[i].zone
            << setw(16) << steps[i].aisle
            << setw(16) << (steps[i].shelf.empty() ? "-" : steps[i].shelf) << endl;
    }
}

NavigationSystem::NavigationSystem() {
    orderID = "";
    robotID = "";
    destination = "";
    itemZone = "";
    itemAisle = "";
    itemShelf = "";
    pathStarted = false;
    itemReached = false;
    srand(time(0));
}

//A new navigation session is initialised using data from other tasks
//Takes the route array generated by Task 5 and pushes each step onto stack to record forward path
void NavigationSystem::startPath(string oID, string rID, string iZone, string iAisle,string iShelf,
                                string dest, stepMovement route[], int routeSize) {
    resetNavigation();
 
    orderID = oID;
    robotID = rID;
    itemZone = iZone;
    itemAisle = iAisle;
    itemShelf = iShelf;
    destination = dest;

    cout << "\n================================================================================" << endl;
    cout << "Navigation Started" << endl;
    cout << "================================================================================" << endl;
    cout << "Robot ID  : " << robotID << endl;
    cout << "Order ID  : " << orderID << endl;
    cout << "Item At   : " << itemZone << " - " << itemAisle << " - " << itemShelf << endl;
    cout << "Deliver To: " << destination << endl;
    cout << "--------------------------------------------------------------------------------" << endl;

    // Push each route step onto the stack
    cout << "\nForward Path - Recording Steps:" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
 
    for (int i = 0; i < routeSize; i++) {
        route[i].stepNumber = i + 1;  // assign step numbers
        if (pathStack.push(route[i])) {
            cout << "Step " << route[i].stepNumber
                 << " : " << route[i].zone;
            if (!route[i].aisle.empty()) {
                cout << " - " << route[i].aisle;
            }
            if (!route[i].shelf.empty()) {
                cout << " - " << route[i].shelf;
            }
            cout << endl;

            //Random obstacle simulation (20% each step)
            if (i < routeSize - 1 && rand() % 5 == 0) {
                cout << "\nObstacle Detected at Step " << route[i].stepNumber << "!" << endl;
                cout << "Path is blocked - initiating backtrack" << endl;
                handleObstacle();

                //Push current steps
                route[i].stepNumber = pathStack.getSize() + 1;
                pathStack.push(route[i]);
                cout << "Resuming path - Step " << route[i].stepNumber << " re-recorded." << endl;
            }
        }
    }

    pathStarted = true;
    itemReached = true;
 
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Robot arrived at: " << itemZone  << " - " << itemAisle << " - " << itemShelf << endl;
    cout << "Item picked up successfully!" << endl;
    cout << "================================================================================" << endl;
}

// ================================================================
//  NAVIGATION SYSTEM — recordStep()
//  Records one manual movement step onto the stack.
//  Used for standalone testing when Task 5 is not yet integrated.
//
//  Time Complexity  : O(1)
//  Space Complexity : O(1)
// ================================================================
bool NavigationSystem::recordStep(string zone,
                                  string aisle,
                                  string shelf) {
    if (pathStack.isFull()) {
        cout << "[Navigation] ERROR: Path is full. Cannot record more steps.\n";
        return false;
    }
 
    stepMovement step;
    step.stepNumber = pathStack.getSize() + 1;
    step.zone       = zone;
    step.aisle      = aisle;
    step.shelf      = shelf;
 
    pathStack.push(step);
 
    cout << "Step "  << step.stepNumber
         << " recorded : " << zone;
    if (!aisle.empty()) cout << " - " << aisle;
    if (!shelf.empty()) cout << " - " << shelf;
    cout << "\n";

    // ---- Random Obstacle Simulation — 20% chance ----
    if (rand() % 5 == 0) {
        cout << "\nObstacle detected at Step "
            << step.stepNumber << "!" << endl;
        cout << "  Path is blocked - initiating backtrack" << endl;
        handleObstacle();
    }

    pathStarted = true;
    return true;
}

void NavigationSystem::displayForwardPath() {
    cout << "\n================================================================================" << endl;
    cout << "Forward Path Log" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Robot : " << robotID << endl;
    cout << "Order : " << orderID << endl;
    cout << "Target: " << itemZone << " - " << itemAisle << " - " << itemShelf << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Total Steps : " << pathStack.getSize() << endl;
 
    pathStack.displayAll();
    cout << "================================================================================" << endl;
}

//Pops all steps from stack and reverses each steps.
//Start from last step to first step
void NavigationSystem::returnPath() {
    if (pathStack.isEmpty()) {
        cout << "No path to reverse. Robot is already at start." << endl;
        return;
    }

    cout << "\n================================================================================" << endl;
    cout << "Return Path - Retracing Path in Reverse" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Robot : " << robotID << endl;
    cout << "Order : " << orderID << endl;
    cout << "Return: " << destination << endl;
    cout << "--------------------------------------------------------------------------------" << endl;

    cout << left
        << setw(8) << "Step"
        << setw(16) << "Zone"
        << setw(16) << "Aisle"
        << setw(16) << "Shelf" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;

    int returnStep = 1;
    while (!pathStack.isEmpty()) {
        stepMovement step = pathStack.pop();

        cout << left
            << setw(8)  << returnStep
            << setw(16) << step.zone
            << setw(16) << (step.aisle.empty() ? "-" : step.aisle)
            << setw(16) << (step.shelf.empty() ? "-" : step.shelf) << endl;
        returnStep++;
    }
 
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << robotID << " has returned to starting position." << endl;
    cout << "Order " << orderID << " completed successfully!" << endl;
    cout << "================================================================================" << endl;

    // Reset after successful return
    pathStarted = false;
    itemReached    = false;
}

//To handle if obstacle is in path
//Pop last step that led to obstacle
//Ask and push the new direction then continue path
bool NavigationSystem::handleObstacle() {
    if (pathStack.isEmpty()) {
        cout << "Navigation cannot backtrack as no steps recorded." << endl;
        return false;
    }

    // Step 1 — Pop last step (backtrack)
    stepMovement last = pathStack.pop();
 
    cout << "\n================================================================================" << endl;
    cout << "Obstacle has been detected! - Backtracking" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Obstacle at Step " << last.stepNumber << " : " << last.zone;
    if (!last.aisle.empty()) {
        cout << " - " << last.aisle;
    }
    if (!last.shelf.empty()) {
        cout << " - " << last.shelf;
    }
    cout << endl;

    // Step 2 — Show current position after backtrack
    cout << "\nRobot backtracked to" << endl;
    if (!pathStack.isEmpty()) {
        stepMovement current = pathStack.peek();
        cout << "  " << current.zone;
        if (!current.aisle.empty()) {
            cout << " - " << current.aisle;
        } 
        if (!current.shelf.empty()) {
            cout << " - " << current.shelf;
        }
    } else {
        cout << "Starting position (no previous steps)";
    }
    cout << endl;
    

    // Step 3 — Ask for new direction
    cout << "\nEnter new direction to avoid obstacle: " << endl;
    string newZone, newAisle, newShelf;
    cout << "Zone  : "; getline(cin, newZone);
    cout << "Aisle : "; getline(cin, newAisle);
    cout << "Shelf : "; getline(cin, newShelf);

    // Step 4 — Push new step onto stack
    stepMovement newStep;
    newStep.stepNumber = pathStack.getSize() + 1;
    newStep.zone       = newZone;
    newStep.aisle      = newAisle;
    newStep.shelf      = newShelf;
 
    pathStack.push(newStep);

    // Step 5 — Confirm new direction recorded
    cout << "\nNew Step " << newStep.stepNumber << " recorded : " << newZone;
    if (!newAisle.empty()) {
        cout << " - " << newAisle;
    }
    if (!newShelf.empty()) {
        cout << " - " << newShelf;
    }
    cout << "\nContinuing path from new location." << endl;
    cout << "Remaining steps in path: " << pathStack.getSize() << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
 
    return true;
}

//Clears all state and empties the stack for the next task
void NavigationSystem::resetNavigation() {
    // Empty the stack by creating a fresh one
    pathStack = stack();
    robotID = "";
    orderID = "";
    destination = "";
    itemZone = "";
    itemAisle = "";
    itemShelf = "";
    pathStarted = false;
    itemReached = false;
 
    cout << "Navigation System reset successful. Ready for next task." << endl;
}

//Show current status of navigation system
void NavigationSystem::displayStatus() {
    cout << "\n================================================================================" << endl;
    cout << "Navigation Status" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Robot ID      : " << (robotID.empty() ? "None" : robotID) << endl;
    cout << "Order ID      : " << (orderID.empty() ? "None" : orderID) << endl;
    cout << "Path Active   : " << (pathStarted ? "Yes" : "No") << endl;
    cout << "Item Reached  : " << (itemReached    ? "Yes" : "No") << endl;
    cout << "Steps Recorded: " << pathStack.getSize() << endl;
 
    if (!pathStack.isEmpty()) {
        stepMovement current = pathStack.peek();
        cout << "  Current Position: " << current.zone;
        if (!current.aisle.empty()) {
            cout << " - " << current.aisle;
        }
        if (!current.shelf.empty()) {
            cout << " - " << current.shelf;
        }
        cout << endl;
    }
    cout << "================================================================================" << endl;
}

//accessor methods
bool NavigationSystem::isPathStarted() { 
    return pathStarted; 
}
bool NavigationSystem::isItemReached(){ 
    return itemReached;
}
string NavigationSystem::getRobotID() { 
    return robotID;
}
string NavigationSystem::getOrderID() { 
    return orderID;
}

void NavigationSystem::navigationMenu() {
    int choice = 0;
 
    while (true) {
        cout << "\n================================================================================" << endl;
        cout << "Robot Navigation & Path Tracking" << endl;
        cout << "================================================================================" << endl;
        cout << "  1. Start New Journey (Manual Input)\n";
        cout << "  2. Record Manual Step" << endl;
        cout << "  3. Display Forward Path" << endl;
        cout << "  4. Execute Return Journey" << endl;
        cout << "  5. Handle Obstacle (Backtrack)" << endl;
        cout << "  6. Display Navigation Status" << endl;
        cout << "  7. Reset Navigation" << endl;
        cout << "  8. Back" << endl;
        cout << "--------------------------------------------------------------------------------" << endl;
        cout << "Enter choice (1-8): ";
        cin  >> choice;
        cin.ignore();
 
        if (choice == 8) {
            cout << "Returning." << endl;
            return;
        }
 
        switch (choice) {
 
            // ---- Option 1: Start New Journey ----
            case 1: {
                string oID, rID, iZone, iAisle, iShelf, dest;
                int    routeSize;
 
                cout << "\nEnter Order ID  : "; getline(cin, oID);
                cout << "Enter Robot ID  : "; getline(cin, rID);
                cout << "Enter Item Zone : "; getline(cin, iZone);
                cout << "Enter Item Aisle: "; getline(cin, iAisle);
                cout << "Enter Item Shelf: "; getline(cin, iShelf);
                cout << "Enter Destination: "; getline(cin, dest);
                cout << "Enter number of route steps: ";
                cin  >> routeSize;
                cin.ignore();
 
                // Build route array from manual input
                // (replaced by Task 5 route during integration)
                stepMovement* route = new stepMovement[routeSize];
                cout << "\nEnter each step (zone aisle shelf): " << endl;
                cout << "Leave aisle/shelf empty (press Enter) if not applicable" << endl;
 
                for (int i = 0; i < routeSize; i++) {
                    cout << "Step " << (i + 1) << ":" << endl;       
                    cout << "Zone     : "; getline(cin, route[i].zone);
                    cout << "Aisle    : "; getline(cin, route[i].aisle);
                    cout << "Shelf    : "; getline(cin, route[i].shelf);
                }
 
                startPath(oID, rID, iZone, iAisle, iShelf,
                             dest, route, routeSize);
                delete[] route;
                break;
            }
 
            // ---- Option 2: Record Manual Step ----
            case 2: {
                if (!pathStarted) {
                    cout << "No active path. Start a path first." << endl;
                    break;
                }
                string zone, aisle, shelf;
                cout << "Zone : "; getline(cin, zone);
                cout << "Aisle: "; getline(cin, aisle);
                cout << "Shelf: "; getline(cin, shelf);
                recordStep(zone, aisle, shelf);
                break;
            }
 
            // ---- Option 3: Display Forward Path ----
            case 3: {
                displayForwardPath();
                break;
            }
 
            // ---- Option 4: Return Journey ----
            case 4: {
                returnPath();
                break;
            }
 
            // ---- Option 5: Handle Obstacle ----
            case 5: {
                handleObstacle();
                break;
            }
 
            // ---- Option 6: Display Status ----
            case 6: {
                displayStatus();
                break;
            }
 
            // ---- Option 7: Reset ----
            case 7: {
                resetNavigation();
                break;
            }
 
            default:
                cout << "Invalid choice. Enter 1 to 8.\n";
                break;
        }
    }
}