#ifndef RobotNav_PathTracking
#define RobotNav_PathTracking

#include <iostream>
#include <string>
using namespace std;

int task3();

//The max steps that the robot can take
const int max_Steps = 1000;

struct stepMovement {
    int stepNumber; 
    string zone; //eg. Zone A, Zone B
    string aisle; //eg. aisle 1, aisle 2
    string shelf; //eg. shelf 1, shelf 2
};

class stack {
    stepMovement steps[max_Steps];
    int top;

    public:
        stack();

        bool push(stepMovement step);
        stepMovement pop();
        stepMovement peek();
        bool isEmpty();
        bool isFull();
        int getSize();
        void displayAll();
};

class NavigationSystem {
    stack pathStack;    //to store all movement steps
    string orderID;     //Get from task 1
    string robotID;     //Get from task 2
    string destination; //Get from task 1
    string itemZone;    //Get from task 4
    string itemAisle;   //Get from task 4
    string itemShelf;   //Get from task 4
    bool pathStarted;
    bool itemReached;

    public:
        NavigationSystem();

        // Start a journey with route from Task 5
        // route[]  — array of stepMovement generated by Task 5
        // routeSize — number of steps in the route
        void startPath(string orderID, string robotID, string itemZone, string itemAisle, 
            string itemShelf, string destination, stepMovement route[], int routeSize);

        // Record one manual step — used for standalone testing
        // when Task 5 route is not yet available
        bool recordStep(string zone,
                        string aisle,
                        string shelf);

        // Display the complete forward path log
        void displayForwardPath();

        // Execute return journey — pops all steps and reverses directions
        void returnPath();

        // Handle obstacle — backtracks one step by popping the stack
        bool handleObstacle();

        // Reset all state for the next robot task
        void resetNavigation();

        // ---- Status & Accessors ----
        void   displayStatus();      // Show current navigation status
        bool   isPathStarted();   // Check if journey is active
        bool   isItemReached();      // Check if robot reached the item
        string getRobotID();         // Get current robot ID
        string getOrderID();         // Get current order ID

        // ---- Menu ----
        void navigationMenu();

};

#endif // RobotNav_PathTracking