#include "RobotNav_PathTracking.hpp"
#include <iomanip>
#include <cstdlib>
#include <ctime>

//stack
stack::stack() {
    top = -1;
}

//Adds a new step movement on top of the stack
bool stack::push(stepMovement step) {
    if (isFull()) {
        cout << "Stack is full, cannot record more steps." << endl;
        return false;
    }
    steps[++top] = step;
    return true;
}

//Removes and returns the top step movement
stepMovement stack::pop() {
    if (isEmpty()) {
        cout << "Stack is empty. No steps to pop" << endl;
        stepMovement empty;
        empty.stepNumber = -1;
        empty.zone = "";
        empty.aisle = "";
        empty.shelf = "";
        return empty;
    }
    return steps[top--];
}

//Returns the top step movement without removing it
stepMovement stack::peek() {
    if (isEmpty()) {
        cout << "Stack is empty. No steps to peek" << endl;
        stepMovement empty;
        empty.stepNumber = -1;
        empty.zone = "";
        empty.aisle = "";
        empty.shelf = "";
        return empty;
    }
    return steps[top];
}

bool stack::isEmpty() {
    return top == -1;
}

bool stack::isFull() {
    return top == max_Steps -1;
}

int stack::getSize() {
    return top + 1;
}

//Prints all steps for the forward path
void stack::displayAll() {
    if (isEmpty()) {
        cout << "No steps recorded." << endl;
        return; 
    }

    cout << left << setfill(' ')
        << setw(8) << "Step"
        << setw(16) << "Zone"
        << setw(16) << "Aisle"
        << setw(16) << "Shelf" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;

    for (int i = 0; i <= top; i++) {
        cout << left
            << setw(8) << steps[i].stepNumber
            << setw(16) << steps[i].zone
            << setw(16) << steps[i].aisle
            << setw(16) << (steps[i].shelf.empty() ? "-" : steps[i].shelf) << endl;
    }
}

NavigationSystem::NavigationSystem() {
    orderID = "";
    robotID = "";
    destination = "";
    itemZone = "";
    itemAisle = "";
    itemShelf = "";
    pathStarted = false;
    itemReached = false;
    srand(time(0));
}

//A new navigation session is initialised using data from other tasks
//Takes the route array generated by Task 5 and pushes each step onto stack to record forward path
void NavigationSystem::startPath(string oID, string rID, string iZone, string iAisle,string iShelf,
                                string dest, stepMovement route[], int routeSize) {
    resetNavigation();
 
    orderID = oID;
    robotID = rID;
    itemZone = iZone;
    itemAisle = iAisle;
    itemShelf = iShelf;
    destination = dest;

    cout << "\n================================================================================" << endl;
    cout << "Navigation Started" << endl;
    cout << "================================================================================" << endl;
    cout << "Robot ID  : " << robotID << endl;
    cout << "Order ID  : " << orderID << endl;
    cout << "Item At   : " << itemZone << " - " << itemAisle << " - " << itemShelf << endl;
    cout << "Deliver To: " << destination << endl;
    cout << "--------------------------------------------------------------------------------" << endl;

    // Push each route step onto the stack
    cout << "\nForward Path - Recording Steps:" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
 
    for (int i = 0; i < routeSize; i++) {
        route[i].stepNumber = i + 1;  // assign step numbers
        if (pathStack.push(route[i])) {
            cout << "Step " << route[i].stepNumber
                 << " : " << route[i].zone;
            if (!route[i].aisle.empty()) {
                cout << " - " << route[i].aisle;
            }
            if (!route[i].shelf.empty()) {
                cout << " - " << route[i].shelf;
            }
            cout << endl;

            //Obstacle simulation
            if (i > 0 && i < routeSize - 1 && rand() % 5 == 0) {
                handleObstacle(route[i]);
            }
        }
    }

    pathStarted = true;
    itemReached = true;
 
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Robot arrived at: " << itemZone  << " - " << itemAisle << " - " << itemShelf << endl;
    cout << "Item picked up successfully!" << endl;
    cout << "================================================================================" << endl;
}

void NavigationSystem::displayForwardPath() {
    cout << "\n================================================================================" << endl;
    cout << "Forward Path Log" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Robot : " << robotID << endl;
    cout << "Order : " << orderID << endl;
    cout << "Target: " << itemZone << " - " << itemAisle << " - " << itemShelf << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Total Steps : " << pathStack.getSize() << endl;
 
    pathStack.displayAll();
    cout << "================================================================================" << endl;
}

//Pops all steps from stack and reverses each steps.
//Start from last step to first step
void NavigationSystem::returnPath() {
    if (pathStack.isEmpty()) {
        cout << "No path to reverse. Robot is already at start." << endl;
        return;
    }

    cout << "\n================================================================================" << endl;
    cout << "Return Path - Retracing Path in Reverse" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Robot : " << robotID << endl;
    cout << "Order : " << orderID << endl;
    cout << "Return: " << destination << endl;
    cout << "--------------------------------------------------------------------------------" << endl;

    cout << left << setfill(' ')
        << setw(8) << "Step"
        << setw(16) << "Zone"
        << setw(16) << "Aisle"
        << setw(16) << "Shelf" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;

    int returnStep = 1;
    while (!pathStack.isEmpty()) {
        stepMovement step = pathStack.pop();

        cout << left
            << setw(8)  << returnStep
            << setw(16) << step.zone
            << setw(16) << (step.aisle.empty() ? "-" : step.aisle)
            << setw(16) << (step.shelf.empty() ? "-" : step.shelf) << endl;
        returnStep++;
    }
 
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << robotID << " has returned to starting position." << endl;
    cout << "Order " << orderID << " completed successfully!" << endl;
    cout << "================================================================================" << endl;

    // Reset after successful return
    pathStarted = false;
    itemReached    = false;
}

//To handle if obstacle is in path
//Pop last step that led to obstacle
//Ask and push the new direction then continue path
void NavigationSystem::handleObstacle(stepMovement currentStep) {
    pathStack.pop();
 
    cout << "\n================================================================================" << endl;
    cout << "Obstacle has been detected! - Backtracking" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Path blocked at: " << currentStep.zone;
    if (!currentStep.aisle.empty()) {
        cout << " - " << currentStep.aisle;
    }
    if (!currentStep.shelf.empty()) {
        cout << " - " << currentStep.shelf;
    } 
    cout << endl;

    if (!pathStack.isEmpty()) {
        stepMovement safeStep = pathStack.peek();
        cout << "Robot backtracked to previous clear location: " << safeStep.zone;
        if (!safeStep.aisle.empty()) {
            cout << " - " << safeStep.aisle;
        } 
        if (!safeStep.shelf.empty()) {
            cout << " - " << safeStep.shelf;
        } 
        cout << endl;
    }

    cout << "Navigating around obstacle. Route cleared." << endl;
    cout << "Resuming planned trajectory." << endl;
    cout << "================================================================================\n" << endl;

    pathStack.push(currentStep);
}

//Clears all state and empties the stack for the next task
void NavigationSystem::resetNavigation() {
    // Empty the stack by creating a fresh one
    pathStack = stack();
    robotID = "";
    orderID = "";
    destination = "";
    itemZone = "";
    itemAisle = "";
    itemShelf = "";
    pathStarted = false;
    itemReached = false;
 
    cout << "Navigation System reset successful. Ready for next task." << endl;
}

//Show current status of navigation system
void NavigationSystem::displayStatus() {
    cout << "\n================================================================================" << endl;
    cout << "Navigation Status" << endl;
    cout << "--------------------------------------------------------------------------------" << endl;
    cout << "Robot ID      : " << (robotID.empty() ? "None" : robotID) << endl;
    cout << "Order ID      : " << (orderID.empty() ? "None" : orderID) << endl;
    cout << "Path Active   : " << (pathStarted ? "Yes" : "No") << endl;
    cout << "Item Reached  : " << (itemReached    ? "Yes" : "No") << endl;
    cout << "Steps Recorded: " << pathStack.getSize() << endl;
 
    if (!pathStack.isEmpty()) {
        stepMovement current = pathStack.peek();
        cout << "  Current Position: " << current.zone;
        if (!current.aisle.empty()) {
            cout << " - " << current.aisle;
        }
        if (!current.shelf.empty()) {
            cout << " - " << current.shelf;
        }
        cout << endl;
    }
    cout << "================================================================================" << endl;
}

//accessor methods
bool NavigationSystem::isPathStarted() { 
    return pathStarted; 
}
bool NavigationSystem::isItemReached(){ 
    return itemReached;
}
string NavigationSystem::getRobotID() { 
    return robotID;
}
string NavigationSystem::getOrderID() { 
    return orderID;
}